---

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Setup repository
  ansible.builtin.include_tasks: "repo-{{ ansible_os_family }}.yml"
  when: "pdns_install_repo | length > 0"
  tags:
    - install
    - repository

- name: Install PowerDNS
  ansible.builtin.include_tasks: install.yml
  tags:
    - install

- name: Get version of PowerDNS instance
  ansible.builtin.include_tasks: inspect.yml
  tags:
    - db
    - mysql
    - sqlite
    - config

- name: Install and configure MySQL database
  ansible.builtin.include_tasks: database-mysql.yml
  when: "pdns_mysql_databases_credentials | length > 0 and inventory_hostname == hostname"
  with_items: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: hostname
  tags:
    - db
    - mysql

- name: Install and configure SQlite database
  ansible.builtin.include_tasks: database-sqlite3.yml
  when: "pdns_sqlite_databases_locations | length > 0"
  tags:
    - db
    - sqlite

- name: Install and configure LMDB database
  ansible.builtin.include_tasks: database-lmdb.yml
  when: "pdns_lmdb_databases_locations | length > 0"
  tags:
    - db
    - lmdb

- name: Build config file
  ansible.builtin.include_tasks: configure.yml
  tags:
    - config

- name: Configure SELinux
  ansible.builtin.include_tasks: selinux.yml
  when: ansible_selinux is defined and ansible_selinux.status == 'enabled'
  tags:
    - selinux
    - config

- name: Start and enable the PowerDNS service
  throttle: 1
  ansible.builtin.service:
    name: "{{ pdns_service_name }}"
    state: "{{ pdns_service_state }}"
    enabled: "{{ pdns_service_enabled }}"
  tags:
    - service
